server:
  port: 8881
spring:
  activityDataSource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/activity?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
